name: Deploy static content to Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          yarn run build
          touch build/.nojekyll

      # Add a step to clean up any potential symlinks
      - name: Clean up symlinks
        run: |
          echo "Removing any symlinks from build directory..."
          find build/ -type l -delete
          echo "Converting any remaining symlinks to copies..."
          find build/ -type l -exec bash -c 'cp --remove-destination "$(readlink -f "$0")" "$0"' {} \;

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Verify downloaded content
        run: |
          echo "Checking for any remaining symlinks..."
          find . -type l
          echo "Listing directory contents..."
          ls -la

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages