# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Set up Node
        uses: actions/setup-node@v4  
        with:
          node-version: 16 
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          yarn run build
          touch build/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4  

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build/
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
        env:
          GITHUB_PAGES: true

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/github-pages

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: ${{ runner.temp }}/github-pages