# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  
      - name: Set up Node
        uses: actions/setup-node@v4  
        with:
          node-version: 16 
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: |
          yarn run build
          touch build/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  
        with:
          path: 'build/'
          
  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2