name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          yarn run build
          touch build/.nojekyll

      # Clean up any symlinks in build output
      - name: Clean up symlinks
        run: |
          echo "Converting any symlinks to regular files..."
          find build/ -type l -exec bash -c 'cp --remove-destination "$(readlink -f "$0")" "$0"' {} \;

      - name: Deploy to GitHub Pages
        run: |
          cd build
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
          # Get the commit message from the last commit
          COMMIT_MESSAGE=$(git log -1 --pretty=%B 2>/dev/null || echo "Deploy to GitHub Pages")
          
          git add -A
          git commit -m "Deploy: $COMMIT_MESSAGE

          Deployed by GitHub Actions at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          Build from commit: ${{ github.sha }}"
          
          git push -f "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
          
          echo "🚀 Deployed successfully to gh-pages branch"